### ISSUE TITLE
[request] zstd support

### ISSUE THREAD

**Issue by arun54321** [Edenhofer/fakepkg#4]
Compress packages with zstd.

**Comment by Edenhofer** [comment]
Thank you for opening an issue. That sounds like a very reasonable suggestion. I implemented this aa70c1752e44ee2df039debf1204930caaffddcc by honoring the environment variable `PKGEXT` akin to makepkg. Furthermore, I switched the default to zstd. I hope this resolved the issue. If not, please feel free to reopen it.
